import type { Post } from "../../types/post";

export const mockPosts: Post[] = [
  {
    id: "1",
    userId: "1",
    username: "tal",
    userProfileImage: "",
    imageUrl: "https://picsum.photos/seed/post1/800/500",
    content: "זה פוסט ראשון לדוגמה עם תמונה וטקסט.",
    likesCount: 12,
    commentsCount: 4,
    createdAt: "2026-03-07T10:00:00.000Z",
    isLiked: true,
    isOwner: true,
  },
  {
    id: "2",
    userId: "2",
    username: "dana",
    userProfileImage: "",
    imageUrl: "https://picsum.photos/seed/post2/800/500",
    content: "פוסט נוסף של משתמש אחר כדי לדמות פיד אמיתי.",
    likesCount: 7,
    commentsCount: 2,
    createdAt: "2026-03-07T11:30:00.000Z",
    isLiked: false,
    isOwner: false,
  },
  {
    id: "3",
    userId: "3",
    username: "noa",
    userProfileImage: "",
    imageUrl: "",
    content: "אפשר גם פוסט בלי תמונה, רק תוכן טקסטואלי.",
    likesCount: 3,
    commentsCount: 1,
    createdAt: "2026-03-07T12:15:00.000Z",
    isLiked: false,
    isOwner: false,
  },
];
